# Generated by Django 2.1.7 on 2019-02-19 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfiguration',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pt_token', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
