# Generated by Django 2.1.5 on 2019-01-25 03:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('story_id', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=255)),
                ('is_reverted', models.BooleanField(default=False)),
                ('origin', models.CharField(choices=[('ADJUST_STORY_ACCEPTED_DATE', 'adjust_accepted_date')], max_length=100)),
                ('changes', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
